/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PromptEngineeringRouteImport } from './routes/prompt-engineering'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as ToolsChatRouteImport } from './routes/tools.chat'
import { Route as ToolsEmailRouteImport } from './routes/tools.email'
import { Route as ToolsMeetingsRouteImport } from './routes/tools.meetings'
import { Route as ToolsResearchRouteImport } from './routes/tools.research'
import { Route as ToolsTasksRouteImport } from './routes/tools.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptEngineeringRoute = PromptEngineeringRouteImport.update({
  id: '/prompt-engineering',
  path: '/prompt-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsChatRoute = ToolsChatRouteImport.update({
  id: '/tools/chat',
  path: '/tools/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEmailRoute = ToolsEmailRouteImport.update({
  id: '/tools/email',
  path: '/tools/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMeetingsRoute = ToolsMeetingsRouteImport.update({
  id: '/tools/meetings',
  path: '/tools/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsResearchRoute = ToolsResearchRouteImport.update({
  id: '/tools/research',
  path: '/tools/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTasksRoute = ToolsTasksRouteImport.update({
  id: '/tools/tasks',
  path: '/tools/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/prompt-engineering': typeof PromptEngineeringRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/tools/chat': typeof ToolsChatRoute
  '/tools/email': typeof ToolsEmailRoute
  '/tools/meetings': typeof ToolsMeetingsRoute
  '/tools/research': typeof ToolsResearchRoute
  '/tools/tasks': typeof ToolsTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/prompt-engineering': typeof PromptEngineeringRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/tools/chat': typeof ToolsChatRoute
  '/tools/email': typeof ToolsEmailRoute
  '/tools/meetings': typeof ToolsMeetingsRoute
  '/tools/research': typeof ToolsResearchRoute
  '/tools/tasks': typeof ToolsTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/prompt-engineering': typeof PromptEngineeringRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/tools/chat': typeof ToolsChatRoute
  '/tools/email': typeof ToolsEmailRoute
  '/tools/meetings': typeof ToolsMeetingsRoute
  '/tools/research': typeof ToolsResearchRoute
  '/tools/tasks': typeof ToolsTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/prompt-engineering'
    | '/responsible-ai'
    | '/tools/chat'
    | '/tools/email'
    | '/tools/meetings'
    | '/tools/research'
    | '/tools/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/prompt-engineering'
    | '/responsible-ai'
    | '/tools/chat'
    | '/tools/email'
    | '/tools/meetings'
    | '/tools/research'
    | '/tools/tasks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/prompt-engineering'
    | '/responsible-ai'
    | '/tools/chat'
    | '/tools/email'
    | '/tools/meetings'
    | '/tools/research'
    | '/tools/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PromptEngineeringRoute: typeof PromptEngineeringRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
  ToolsChatRoute: typeof ToolsChatRoute
  ToolsEmailRoute: typeof ToolsEmailRoute
  ToolsMeetingsRoute: typeof ToolsMeetingsRoute
  ToolsResearchRoute: typeof ToolsResearchRoute
  ToolsTasksRoute: typeof ToolsTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-engineering': {
      id: '/prompt-engineering'
      path: '/prompt-engineering'
      fullPath: '/prompt-engineering'
      preLoaderRoute: typeof PromptEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/chat': {
      id: '/tools/chat'
      path: '/tools/chat'
      fullPath: '/tools/chat'
      preLoaderRoute: typeof ToolsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/email': {
      id: '/tools/email'
      path: '/tools/email'
      fullPath: '/tools/email'
      preLoaderRoute: typeof ToolsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/meetings': {
      id: '/tools/meetings'
      path: '/tools/meetings'
      fullPath: '/tools/meetings'
      preLoaderRoute: typeof ToolsMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/research': {
      id: '/tools/research'
      path: '/tools/research'
      fullPath: '/tools/research'
      preLoaderRoute: typeof ToolsResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tasks': {
      id: '/tools/tasks'
      path: '/tools/tasks'
      fullPath: '/tools/tasks'
      preLoaderRoute: typeof ToolsTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PromptEngineeringRoute: PromptEngineeringRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
  ToolsChatRoute: ToolsChatRoute,
  ToolsEmailRoute: ToolsEmailRoute,
  ToolsMeetingsRoute: ToolsMeetingsRoute,
  ToolsResearchRoute: ToolsResearchRoute,
  ToolsTasksRoute: ToolsTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
